apiVersion: apps/v1
kind: Deployment
metadata: 
  name: echotech-api-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echotechapiservice
  template:
    metadata:
      labels:
        app: echotechapiservice
    spec:
      containers:
        - name: echotechservice
          image: prashantdarade1697/echotechapiservice
          resources:
            requests:
              memory: "512Mi"       
              cpu: "500m"           
            limits:
              memory: "1Gi"      
              cpu: "1"  
          env:
          - name: EchoTechServer
            value: "mssql-clusterip"
          - name: EchoTechDataBase
            value: "EchoTech"
          - name: EchoTechUserId
            value: "SA"                 
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: mssql-secrets
                key: MSSQL_SA_PASSWORD

---
apiVersion: v1
kind: Service
metadata: 
  name: echotech-api-clusterip
spec:
  type: ClusterIP
  selector:
    app: echotechapiservice
  ports:
   - name: echotechapiservice
     protocol: TCP
     port: 80
     targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: echotech-api-nodeport-service
spec:
  type: NodePort
  selector:
    app: echotechapiservice
  ports:
    - name: echotechapiservice
      protocol: TCP
      port: 80
      targetPort: 80